//
//  FavoriteBasic.swift
//  ExaminationScheduleApp
//
//  Created by user on 2022/03/11.
//

import SwiftUI

var FavoriteBasicArray: [ExamBasic1] = FavoriteMakeData()

func FavoriteMakeData() -> [ExamBasic1] {
    var dataArray: [ExamBasic1] = []
    
    dataArray.append(ExamBasic1(id: 0, title: "北海道警察", like: false, url: "https://www.police.pref.hokkaido.lg.jp/info/keimu/saiyou/police/top.html"))
    dataArray.append(ExamBasic1(id: 1, title: "青森県警察", like: false, url: "https://www.police.pref.aomori.jp/keimubu/keimu/saiyo_index.html"))
    dataArray.append(ExamBasic1(id: 2, title: "秋田県警察", like: false, url: "https://www.police.pref.akita.lg.jp/recruit"))
    dataArray.append(ExamBasic1(id: 3, title: "岩手県警察", like: false, url: "http://www2.pref.iwate.jp/~hp0802/oshirase/keimu/saiyo/00top/top.html"))
    dataArray.append(ExamBasic1(id: 4, title: "山形県警察", like: false, url: "https://www.pref.yamagata.jp/800003/kensei/police/boshuu/employments/employment.html"))
    dataArray.append(ExamBasic1(id: 5, title: "宮城県警察", like: false, url: "https://www.police.pref.miyagi.jp/hp/keimu/police/index.html"))
    dataArray.append(ExamBasic1(id: 6, title: "福島県警察", like: false, url: "https://www.pref.fukushima.lg.jp/site/saiyou/"))
    dataArray.append(ExamBasic1(id: 7, title: "新潟県警察", like: false, url: "https://www.pref.niigata.lg.jp/site/kenkei-saiyo/"))
    dataArray.append(ExamBasic1(id: 8, title: "茨城県警察", like: false, url: "https://www.pref.ibaraki.jp/kenkei/saiyo/ibarakipc_site/"))
    dataArray.append(ExamBasic1(id: 9, title: "栃木県警察", like: false, url: "https://www.pref.tochigi.lg.jp/keisatu/saiyou/index.html"))
    dataArray.append(ExamBasic1(id: 10, title: "群馬県警察", like: false, url: "https://www.police.pref.gunma.jp/gp-saiyou/index.htm"))
    dataArray.append(ExamBasic1(id: 11, title: "千葉県警察", like: false, url: "https://www.police.pref.chiba.jp/keimuka/recruit_adoption.html"))
    dataArray.append(ExamBasic1(id: 12, title: "埼玉県警察", like: false, url: "https://www.police.pref.saitama.lg.jp/saiyo/index.html"))
    dataArray.append(ExamBasic1(id: 13, title: "東京都警視庁", like: false, url: "https://www.keishicho.metro.tokyo.lg.jp/saiyo/2021/"))
    dataArray.append(ExamBasic1(id: 14, title: "神奈川県警察", like: false, url: "https://www.police.pref.kanagawa.jp/mes/mesb0001.htm"))
    dataArray.append(ExamBasic1(id: 15, title: "山梨県警察", like: false, url: "https://www.pref.yamanashi.jp/police/saiyou/index.html"))
    dataArray.append(ExamBasic1(id: 16, title: "長野県警察", like: false, url: "https://www.police.pref.nagano.lg.jp/"))
    dataArray.append(ExamBasic1(id: 17, title: "静岡県警察", like: false, url: "https://www.pref.shizuoka.jp/police/saiyo/index.html"))
    dataArray.append(ExamBasic1(id: 18, title: "富山県警察", like: false, url: "https://police.pref.toyama.jp/shoukai/shokuin/index.html"))
    dataArray.append(ExamBasic1(id: 19, title: "岐阜県警察", like: false, url: "https://www.pref.gifu.lg.jp/site/police/16930.html"))
    dataArray.append(ExamBasic1(id: 20, title: "愛知県警察", like: false, url: "https://www.pref.aichi.jp/police/syokai/saiyou/"))
    dataArray.append(ExamBasic1(id: 21, title: "石川県警察", like: false, url: "http://www.pref.ishikawa.jp/jinjiiin/"))
    dataArray.append(ExamBasic1(id: 22, title: "福井県警察", like: false, url: "https://www.pref.fukui.lg.jp/kenkei/doc/kenkei/test.html"))
    dataArray.append(ExamBasic1(id: 23, title: "三重県警察", like: false, url: "https://www.police.pref.mie.jp/recruit/"))
    dataArray.append(ExamBasic1(id: 24, title: "滋賀県警察", like: false, url: "https://www.pref.shiga.lg.jp/police/osirase/saiyou/104771.html"))
    dataArray.append(ExamBasic1(id: 25, title: "京都府警察", like: false, url: "https://www.pref.kyoto.jp/fukei/shokai/saiyo/index.html"))
    dataArray.append(ExamBasic1(id: 26, title: "大阪府警察", like: false, url: "https://www.police.pref.osaka.lg.jp/saiyo/index.html"))
    dataArray.append(ExamBasic1(id: 27, title: "奈良県警察", like: false, url: "https://www.police.pref.nara.jp/category/5-0-0-0-0.html"))
    dataArray.append(ExamBasic1(id: 28, title: "和歌山県警察", like: false, url: "https://www.police.pref.wakayama.lg.jp/recruit/index.html"))
    dataArray.append(ExamBasic1(id: 29, title: "兵庫県警察", like: false, url: "https://www.police.pref.hyogo.lg.jp/saiyo/"))
    dataArray.append(ExamBasic1(id: 30, title: "鳥取県警察", like: false, url: "https://www.pref.tottori.lg.jp/153468.htm"))
    dataArray.append(ExamBasic1(id: 31, title: "島根県警察", like: false, url: "https://www.pref.shimane.lg.jp/police/07_police_introduction/careers/"))
    dataArray.append(ExamBasic1(id: 32, title: "岡山県警察", like: false, url: "https://www.pref.okayama.jp/site/376/"))
    dataArray.append(ExamBasic1(id: 33, title: "広島県警察", like: false, url: "https://www.pref.hiroshima.lg.jp/site/saiyou/index.html"))
    dataArray.append(ExamBasic1(id: 34, title: "山口県警察", like: false, url: "https://www.police.pref.yamaguchi.lg.jp/saiyou/index.html"))
    dataArray.append(ExamBasic1(id: 35, title: "徳島県警察", like: false, url: "https://www.police.pref.tokushima.jp/11saiyou/index.html"))
    dataArray.append(ExamBasic1(id: 36, title: "香川県警察", like: false, url: "https://www.pref.kagawa.lg.jp/police/ksjinji/saiyou/index.html"))
    dataArray.append(ExamBasic1(id: 37, title: "愛媛県警察", like: false, url: "http://www.police.pref.ehime.jp/mobile/s/index.html"))
    dataArray.append(ExamBasic1(id: 38, title: "高知県警察", like: false, url: "https://www.police.pref.kochi.lg.jp/sections/keimu/jinji/saiyou0.html"))
    dataArray.append(ExamBasic1(id: 39, title: "福岡県警察", like: false, url: "https://www.police.pref.fukuoka.jp/saiyou/"))
    dataArray.append(ExamBasic1(id: 40, title: "佐賀県警察", like: false, url: "https://www.police.pref.saga.jp/recruit/saiyo.html"))
    dataArray.append(ExamBasic1(id: 41, title: "長崎県警察", like: false, url: "https://www.police.pref.nagasaki.jp/recruit/recruit01.html"))
    dataArray.append(ExamBasic1(id: 42, title: "熊本県警察", like: false, url: "https://www.pref.kumamoto.jp/site/police/list17-64.html"))
    dataArray.append(ExamBasic1(id: 43, title: "宮崎県警察", like: false, url: "https://www.pref.miyazaki.lg.jp/police/saiyo/index.html "))
    dataArray.append(ExamBasic1(id: 44, title: "大分県警察", like: false, url: "https://www.pref.oita.jp/site/keisatu-saiyou/"))
    dataArray.append(ExamBasic1(id: 45, title: "鹿児島県警察", like: false, url: "https://www.pref.kagoshima.jp/ja07/police/saiyo/index.html"))
    dataArray.append(ExamBasic1(id: 46, title: "沖縄県警察", like: false, url: "https://www.police.pref.okinawa.jp/docs/2015022300463/"))
    dataArray.append(ExamBasic1(id: 47, title: "北海道札幌市消防局", like: false, url: "https://www.city.sapporo.jp/shobo/saiyo/top.html"))
    dataArray.append(ExamBasic1(id: 48, title: "宮城県仙台市消防局", like: false, url: "https://www.city.sendai.jp/ninyo/shise/shokuin/saiyo/shikenjoho/index.html"))
    dataArray.append(ExamBasic1(id: 49, title: "埼玉県さいたま市消防局", like: false, url: "https://www.city.saitama.jp/006/001/001/index.html"))
    dataArray.append(ExamBasic1(id: 50, title: "東京消防庁", like: false, url: "https://www.tfd.metro.tokyo.lg.jp/bsy/index.html"))
    dataArray.append(ExamBasic1(id: 51, title: "千葉県千葉市消防局", like: false, url: "https://www.city.chiba.jp/shobo/somu/jinji/saiyou.html"))
    dataArray.append(ExamBasic1(id: 52, title: "神奈川県横浜市消防局", like: false, url: "https://www.city.yokohama.lg.jp/kurashi/bousai-kyukyu-bohan/shobo/saiyo/saiyou.html"))
    dataArray.append(ExamBasic1(id: 53, title: "神奈川県川崎市消防局", like: false, url: "https://www.city.kawasaki.jp/shisei/category/61-1-0-0-0-0-0-0-0-0.html"))
    dataArray.append(ExamBasic1(id: 54, title: "神奈川県相模原市消防局", like: false, url: "https://www.city.sagamihara.kanagawa.jp/shisei/shokuin_annai/shiyakusho/1018724.html"))
    dataArray.append(ExamBasic1(id: 55, title: "新潟県新潟市消防本部", like: false, url: "https://www.city.niigata.lg.jp/kurashi/bohan/shobo/kohoibentokousyukai/saiyo/index.html"))
    dataArray.append(ExamBasic1(id: 56, title: "静岡県静岡市消防局", like: false, url: "https://shizuoka-city-saiyou.jp/examinfo/"))
    dataArray.append(ExamBasic1(id: 57, title: "静岡県浜松市消防局", like: false, url: "https://www.city.hamamatsu.shizuoka.jp/shise/shokuinsaiyo/index.html"))
    dataArray.append(ExamBasic1(id: 58, title: "愛知県名古屋市消防局", like: false, url: "https://www.city.nagoya.jp/shisei/category/65-21-0-0-0-0-0-0-0-0.html"))
    dataArray.append(ExamBasic1(id: 59, title: "京都府京都市消防局", like: false, url: "https://www.city.kyoto.lg.jp/shobo/page/0000117633.html"))
    dataArray.append(ExamBasic1(id: 60, title: "大阪府大阪市消防局", like: false, url: "https://www.city.osaka.lg.jp/shisei/category/3057-1-12-0-0-0-0-0-0-0.html"))
    dataArray.append(ExamBasic1(id: 61, title: "大阪府堺市消防局", like: false, url: "https://www.city.sakai.lg.jp/kurashi/bosai/shobo/shokai/saiyo/index.html"))
    dataArray.append(ExamBasic1(id: 62, title: "兵庫県神戸市消防局", like: false, url: "https://www.city.kobe.lg.jp/a81137/shise/shokuinsaiyou/recruit/saiyou.html"))
    dataArray.append(ExamBasic1(id: 63, title: "岡山県岡山市消防局", like: false, url: "https://www.city.okayama.jp/shisei/0000005885.html"))
    dataArray.append(ExamBasic1(id: 64, title: "広島県広島市消防局", like: false, url: "https://www.city.hiroshima.lg.jp/site/shobo/12019.html"))
    dataArray.append(ExamBasic1(id: 65, title: "福岡県北九州市消防局", like: false, url: "https://city-kitakyushu-saiyo.jp/shiken/"))
    dataArray.append(ExamBasic1(id: 66, title: "福岡県福岡市消防局", like: false, url: "https://www.city.fukuoka.lg.jp/syobo/shokuin/shokuin/shokuin.html"))
    dataArray.append(ExamBasic1(id: 67, title: "熊本県熊本市消防局", like: false, url: "https://www.city.kumamoto.jp/hpkiji/pub/detail.aspx?c_id=5&id=2446"))
    dataArray.append(ExamBasic1(id: 68, title: "国家総合・一般", like: false, url: "http://www2.pref.iwate.jp/~hp0741/"))
    dataArray.append(ExamBasic1(id: 69, title: "財務専門官", like: false, url: "https://www.mof.go.jp/about_mof/recruit/zaimu/zaimusenmonkan/index.htm"))
    dataArray.append(ExamBasic1(id: 70, title: "国税専門官", like: false, url: "https://www.nta.go.jp/about/recruitment/kokusen/02.htm"))
    dataArray.append(ExamBasic1(id: 71, title: "労働基準監督官", like: false, url: "https://www.mhlw.go.jp/general/saiyo/kantokukan.html"))
    dataArray.append(ExamBasic1(id: 72, title: "航空管制官", like: false, url: "https://www.mlit.go.jp/koku/atc/shiken.html"))
    dataArray.append(ExamBasic1(id: 73, title: "自衛隊", like: false, url: "https://www.mod.go.jp/gsdf/jieikanbosyu/"))
    dataArray.append(ExamBasic1(id: 74, title: "海上保安庁", like: false, url: "https://www.kaiho.mlit.go.jp/recruitment/"))
    dataArray.append(ExamBasic1(id: 75, title: "皇宮護衛官", like: false, url: "https://www.npa.go.jp/kougu/recruit/exam/index.html"))
    dataArray.append(ExamBasic1(id: 76, title: "刑務官", like: false, url: "https://www.moj.go.jp/kyousei1/kyousei_kyouse13.html"))
    dataArray.append(ExamBasic1(id: 77, title: "入国警備官", like: false, url: "https://www.moj.go.jp/isa/supply/recruitment/nyukan_nyukan06.html"))
    dataArray.append(ExamBasic1(id: 78, title: "北海道庁", like: false, url: "https://www.pref.hokkaido.lg.jp/category/d004/c009/s019/"))
    dataArray.append(ExamBasic1(id: 79, title: "青森県庁", like: false, url: "https://www.pref.aomori.lg.jp/saiyo_shokuin/"))
    dataArray.append(ExamBasic1(id: 80, title: "秋田県庁", like: false, url: "https://www.pref.akita.lg.jp/pages/archive/1295"))
    dataArray.append(ExamBasic1(id: 81, title: "岩手県庁", like: false, url: "http://www2.pref.iwate.jp/~hp0741/"))
    dataArray.append(ExamBasic1(id: 82, title: "山形県庁", like: false, url: "https://www.pref.yamagata.jp/930001/kensei/recruit/saiyoujouhou/kennoshokuin/saiyosikentop/index.html"))
    dataArray.append(ExamBasic1(id: 83, title: "宮城県庁", like: false, url: "https://www.pref.miyagi.jp/site/saiyou/"))
    dataArray.append(ExamBasic1(id: 84, title: "福島県庁", like: false, url: "https://www.pref.fukushima.lg.jp/site/saiyou/"))
    dataArray.append(ExamBasic1(id: 85, title: "新潟県庁", like: false, url: "https://www.pref.niigata.lg.jp/life/7/33/"))
    dataArray.append(ExamBasic1(id: 86, title: "茨城県庁", like: false, url: "https://www.pref.ibaraki.jp/jinjiiin/saiyojyoho.html"))
    dataArray.append(ExamBasic1(id: 87, title: "栃木県庁", like: false, url: "https://www.pref.tochigi.lg.jp/k02/pref/saiyou/kenshokuin/top.html"))
    dataArray.append(ExamBasic1(id: 88, title: "群馬県庁", like: false, url: "https://www.pref.gunma.jp/cate_list/ct00006211.html"))
    dataArray.append(ExamBasic1(id: 89, title: "千葉県庁", like: false, url: "https://www.pref.chiba.lg.jp/jinji/ninyou/saiyoushiken/index.html"))
    dataArray.append(ExamBasic1(id: 90, title: "埼玉県庁", like: false, url: "https://www.pref.saitama.lg.jp/f1903/saiyou/index.html"))
    dataArray.append(ExamBasic1(id: 91, title: "東京都庁", like: false, url: "https://www.saiyou2.metro.tokyo.lg.jp/pc/"))
    dataArray.append(ExamBasic1(id: 92, title: "神奈川県庁", like: false, url: "https://www.pref.kanagawa.jp/docs/s3u/saiyou/index.html"))
    dataArray.append(ExamBasic1(id: 93, title: "山梨県庁", like: false, url: "https://www.pref.yamanashi.jp/jinji-iin/saiyou/"))
    dataArray.append(ExamBasic1(id: 94, title: "長野県庁", like: false, url: "https://www.pref.nagano.lg.jp/jinjii/kensei/soshiki/soshiki/boshu/index.html"))
    dataArray.append(ExamBasic1(id: 95, title: "静岡県庁", like: false, url: "https://www.pref.shizuoka.jp/zinzi/employ/"))
    dataArray.append(ExamBasic1(id: 96, title: "富山県庁", like: false, url: "https://www.pref.toyama.jp/sections/0300/recruit/index.html"))
    dataArray.append(ExamBasic1(id: 97, title: "岐阜県庁", like: false, url: "https://www.pref.gifu.lg.jp/page/3703.html"))
    dataArray.append(ExamBasic1(id: 98, title: "愛知県庁", like: false, url: "https://www.pref.aichi.jp/jinji/syokuin/sp/"))
    dataArray.append(ExamBasic1(id: 99, title: "石川県庁", like: false, url: "http://www.pref.ishikawa.jp/jinjiiin/"))
    dataArray.append(ExamBasic1(id: 101, title: "福井県庁", like: false, url: "http://info.pref.fukui.jp/jinji-i/"))
    dataArray.append(ExamBasic1(id: 102, title: "三重県庁", like: false, url: "https://www.pref.mie.lg.jp/saiyo/index.htm"))
    dataArray.append(ExamBasic1(id: 103, title: "滋賀県庁", like: false, url: "https://www.pref.shiga.lg.jp/kensei/jinji/saiyou/"))
    dataArray.append(ExamBasic1(id: 104, title: "京都府庁", like: false, url: "https://www.pref.kyoto.jp/recruit/"))
    dataArray.append(ExamBasic1(id: 105, title: "大阪府庁", like: false, url: "https://www.pref.osaka.lg.jp/jinji-i/saiyo/"))
    dataArray.append(ExamBasic1(id: 106, title: "奈良県庁", like: false, url: "https://www.pref.nara.jp/9723.htm"))
    dataArray.append(ExamBasic1(id: 107, title: "和歌山県庁", like: false, url: "https://www.pref.wakayama.lg.jp/prefg/210100/saiyou.html"))
    dataArray.append(ExamBasic1(id: 108, title: "兵庫県庁", like: false, url: "https://web.pref.hyogo.lg.jp/pref/cate2_616.html"))
    dataArray.append(ExamBasic1(id: 109, title: "鳥取県庁", like: false, url: "https://www.pref.tottori.lg.jp/98514.htm"))
    dataArray.append(ExamBasic1(id: 110, title: "島根県庁", like: false, url: "https://www.pref.shimane.lg.jp/admin/syokuin/saiyou/saiyou_info/"))
    dataArray.append(ExamBasic1(id: 111, title: "岡山県庁", like: false, url: "https://www.pref.okayama.jp/page/detail-29285.html"))
    dataArray.append(ExamBasic1(id: 112, title: "広島県庁", like: false, url: "https://www.pref.hiroshima.lg.jp/site/recruit/"))
    dataArray.append(ExamBasic1(id: 113, title: "山口県庁", like: false, url: "https://www.pref.yamaguchi.lg.jp/cms/a33000/shiken/saiyo-joho_sp.html"))
    dataArray.append(ExamBasic1(id: 114, title: "徳島県庁", like: false, url: "https://www.pref.tokushima.lg.jp/saiyou/"))
    dataArray.append(ExamBasic1(id: 115, title: "香川県庁", like: false, url: "https://www.pref.kagawa.lg.jp/jinjii/saiyou/kfvn.html"))
    dataArray.append(ExamBasic1(id: 116, title: "愛媛県庁", like: false, url: "https://www.pref.ehime.jp/employment/"))
    dataArray.append(ExamBasic1(id: 117, title: "高知県庁", like: false, url: "https://www.pref.kochi.lg.jp/saiyou/"))
    dataArray.append(ExamBasic1(id: 118, title: "福岡県庁", like: false, url: "https://www.pref.fukuoka.lg.jp/contents/saiyo.html"))
    dataArray.append(ExamBasic1(id: 119, title: "佐賀県庁", like: false, url: "https://saga-saiyou.net/"))
    dataArray.append(ExamBasic1(id: 120, title: "長崎県庁", like: false, url: "https://www.pref.nagasaki.jp/object/shikaku-shiken-bosyu/shokuinsaiyo-shikaku-shiken-bosyu/"))
    dataArray.append(ExamBasic1(id: 121, title: "熊本県庁", like: false, url: "https://www.pref.kumamoto.jp/site/saiyou/list33.html"))
    dataArray.append(ExamBasic1(id: 122, title: "宮崎県庁", like: false, url: "https://www.pref.miyazaki.lg.jp/contents/org/kakushu/jinji/shokuin_boshu/index.html "))
    dataArray.append(ExamBasic1(id: 123, title: "大分県庁", like: false, url: "https://www.pref.oita.jp/site/saiyouzyouhou/"))
    dataArray.append(ExamBasic1(id: 124, title: "鹿児島県庁", like: false, url: "https://saiyo.pref.kagoshima.jp/"))
    dataArray.append(ExamBasic1(id: 125, title: "沖縄県庁", like: false, url: "https://www.pref.okinawa.jp/site/jinji_i/8481.html"))
    dataArray.append(ExamBasic1(id: 126, title: "東京都23区", like: false, url: "http://www.tokyo23city.or.jp/saiyou-siken.htm"))
    dataArray.append(ExamBasic1(id: 127, title: "東京都八王子市", like: false, url: "https://www.city.hachioji.tokyo.jp/contents/saiyou/index.html"))
    dataArray.append(ExamBasic1(id: 128, title: "東京都立川市", like: false, url: "https://www.city.tachikawa.lg.jp/shise/saiyo/index.html"))
    dataArray.append(ExamBasic1(id: 129, title: "東京都武蔵野市", like: false, url: "http://www.city.musashino.lg.jp/shisei_joho/jinji_saiyo/saiyo/index.html"))
    dataArray.append(ExamBasic1(id: 130, title: "東京都三鷹市", like: false, url: "https://www.city.mitaka.lg.jp/c_categories/index05002002.html"))
    dataArray.append(ExamBasic1(id: 131, title: "東京都青梅市", like: false, url: "https://www.city.ome.tokyo.jp/life/3/29/155/"))
    dataArray.append(ExamBasic1(id: 132, title: "東京都府中市", like: false, url: "https://www.city.fuchu.tokyo.jp/gyosei/jinji/index.html"))
    dataArray.append(ExamBasic1(id: 133, title: "東京都昭島市", like: false, url: "https://www.city.akishima.lg.jp/li/060/090/010/index.html"))
    dataArray.append(ExamBasic1(id: 134, title: "東京都調布市", like: false, url: "https://www.city.chofu.tokyo.jp/www/genre/0000000000000/1000000010237/index.html"))
    dataArray.append(ExamBasic1(id: 135, title: "東京都町田市", like: false, url: "https://www.city.machida.tokyo.jp/shisei/syokuin/bosyu01/index.html"))
    dataArray.append(ExamBasic1(id: 136, title: "東京都小金井市", like: false, url: "https://www.city.koganei.lg.jp/smph/shisei/syokuinsaiyoujouhou/index.html"))
    dataArray.append(ExamBasic1(id: 137, title: "東京都小平市", like: false, url: "https://www.city.kodaira.tokyo.jp/kurashi/index07007.html"))
    dataArray.append(ExamBasic1(id: 138, title: "東京都日野市", like: false, url: "https://www.city.hino.lg.jp/shisei/saiyou/index.html"))
    dataArray.append(ExamBasic1(id: 139, title: "東京都東村山市", like: false, url: "https://www.city.higashimurayama.tokyo.jp/shisei/shokuin/shokuinsaiyo/index.html"))
    dataArray.append(ExamBasic1(id: 140, title: "東京都国分寺市", like: false, url: "https://www.city.kokubunji.tokyo.jp/shokuin/"))
    dataArray.append(ExamBasic1(id: 141, title: "東京都国立市", like: false, url: "https://www.city.kunitachi.tokyo.jp/sub3/"))
    dataArray.append(ExamBasic1(id: 142, title: "東京都福生市", like: false, url: "https://www.city.fussa.tokyo.jp/municipal/soshiki/saiyou/index.html"))
    dataArray.append(ExamBasic1(id: 143, title: "東京都狛江市", like: false, url: "https://www.city.komae.tokyo.jp/index.cfm/46,0,374,2236,html"))
    dataArray.append(ExamBasic1(id: 144, title: "東京都東大和市", like: false, url: "https://www.city.higashiyamato.lg.jp/index.cfm/36,111486,386,672,html"))
    dataArray.append(ExamBasic1(id: 145, title: "東京都清瀬市", like: false, url: "https://www.city.kiyose.lg.jp/siseijouhou/syokuinbosyuu/index.html"))
    dataArray.append(ExamBasic1(id: 146, title: "東京都東久留米市", like: false, url: "https://www.city.higashikurume.lg.jp/shisei/shokuin/seiki/index.html"))
    dataArray.append(ExamBasic1(id: 147, title: "東京都武蔵村山市", like: false, url: "https://www.city.musashimurayama.lg.jp/shisei/boshu/shokuinsaiyo/index.html"))
    dataArray.append(ExamBasic1(id: 148, title: "東京都多摩市", like: false, url: "https://www.city.tama.lg.jp/category/2-4-6-0-0.html"))
    dataArray.append(ExamBasic1(id: 149, title: "東京都稲城市", like: false, url: "https://www.city.inagi.tokyo.jp/smph/shisei/boshuu/syokuin_bosyu/index.html"))
    dataArray.append(ExamBasic1(id: 150, title: "東京都羽村市", like: false, url: "https://www.city.hamura.tokyo.jp/category/3-2-9-0-0-0-0-0-0-0.html"))
    dataArray.append(ExamBasic1(id: 151, title: "東京都あきる野市", like: false, url: "https://www.city.akiruno.tokyo.jp/category/2-2-3-0-0.html"))
    dataArray.append(ExamBasic1(id: 152, title: "東京都西東京市", like: false, url: "https://www.city.nishitokyo.lg.jp/siseizyoho/saiyo/shishokuin/index.html"))
    dataArray.append(ExamBasic1(id: 153, title: "北海道札幌市", like: false, url: "https://www.city.sapporo.jp/jinji-iinkai/saiyo/"))
    dataArray.append(ExamBasic1(id: 154, title: "宮城県仙台市", like: false, url: "http://www.city.sendai.jp/ninyo/shise/shokuin/saiyo/shikenjoho/index.html"))
    dataArray.append(ExamBasic1(id: 155, title: "埼玉県さいたま市", like: false, url: "https://www.city.saitama.jp/006/001/001/index.html"))
    dataArray.append(ExamBasic1(id: 156, title: "千葉県千葉市", like: false, url: "https://www.city.chiba.jp/jinji/boshu/"))
    dataArray.append(ExamBasic1(id: 157, title: "神奈川県横浜市", like: false, url: "https://www.city.yokohama.lg.jp/city-info/saiyo-jinji/saiyo/"))
    dataArray.append(ExamBasic1(id: 158, title: "神奈川県川崎市", like: false, url: "https://www.city.kawasaki.jp/shisei/category/61-1-0-0-0-0-0-0-0-0.html"))
    dataArray.append(ExamBasic1(id: 159, title: "神奈川県相模原市", like: false, url: "https://www.city.sagamihara.kanagawa.jp/shisei/shokuin_annai/index.html"))
    dataArray.append(ExamBasic1(id: 160, title: "新潟県新潟市", like: false, url: "https://www.city.niigata.lg.jp/smph/shisei/soshiki/saiyo/shokuinsaiyo/index.html"))
    dataArray.append(ExamBasic1(id: 161, title: "静岡県静岡市", like: false, url: "https://shizuoka-city-saiyou.jp/"))
    dataArray.append(ExamBasic1(id: 162, title: "静岡県浜松市", like: false, url: "https://www.city.hamamatsu.shizuoka.jp/shise/shokuinsaiyo/index.html"))
    dataArray.append(ExamBasic1(id: 163, title: "愛知県名古屋市", like: false, url: "https://www.city.nagoya.jp/shisei/category/65-21-0-0-0-0-0-0-0-0.html"))
    dataArray.append(ExamBasic1(id: 164, title: "京都府京都市", like: false, url: "https://www.city.kyoto.lg.jp/menu5/category/71-2-0-0-0-0-0-0-0-0.html"))
    dataArray.append(ExamBasic1(id: 165, title: "大阪府大阪市", like: false, url: "https://www.pref.osaka.lg.jp/jinji-i/saiyo/"))
    dataArray.append(ExamBasic1(id: 166, title: "大阪府堺市", like: false, url: "https://www.city.sakai.lg.jp/shisei/jinji/shokuinsaiyo/saiyoannai/index.html"))
    dataArray.append(ExamBasic1(id: 167, title: "兵庫県神戸市", like: false, url: "https://www.city.kobe.lg.jp/a14057/shise/shokuinsaiyou/index.html"))
    dataArray.append(ExamBasic1(id: 168, title: "岡山県岡山市庁", like: false, url: "https://www.city.okayama.jp/shisei/0000017696.html"))
    dataArray.append(ExamBasic1(id: 169, title: "広島県広島市", like: false, url: "https://www.city.hiroshima.lg.jp/site/employment/"))
    dataArray.append(ExamBasic1(id: 170, title: "福岡県北九州市", like: false, url: "https://www.city.kitakyushu.lg.jp/shisei/menu05_0060.html"))
    dataArray.append(ExamBasic1(id: 171, title: "福岡県福岡市", like: false, url: "https://www.city.fukuoka.lg.jp/jinji-iinkai/ninyo/shisei/saiyou.html"))
    dataArray.append(ExamBasic1(id: 172, title: "熊本県熊本市", like: false, url: "https://www.city.kumamoto.jp/hpkiji/pub/detail.aspx?c_id=5&id=2446"))
    
    return dataArray
}
